# Generated by Django 5.2.6 on 2026-03-10 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_user_date_joined_alter_user_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Valor')),
                ('criado_em', models.DateField(auto_now_add=True, verbose_name='Criado em')),
                ('desativado_em', models.DateField(blank=True, null=True, verbose_name='Desativado em')),
                ('status', models.IntegerField(choices=[(1, 'Ativado'), (2, 'Desativado')], default=1, verbose_name='Status')),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Assinatura',
                'verbose_name_plural': 'Assinaturas',
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Valor')),
                ('vencimento', models.DateField(blank=True, verbose_name='Vencimento em')),
                ('status', models.IntegerField(choices=[(1, 'Pendente'), (2, 'Pago'), (3, 'Atrasado')], default=1, verbose_name='Satus')),
                ('assinatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.assinatura', verbose_name='Assinatura')),
            ],
        ),
    ]
