# Generated by Django 5.2.6 on 2026-03-11 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_assinatura_pagamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
