# Generated by Django 5.2.6 on 2026-03-15 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_plano'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoTreino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome do tipo')),
            ],
            options={
                'verbose_name': 'Tipo de treino',
                'verbose_name_plural': 'Tipos dos treinos',
            },
        ),
        migrations.AlterField(
            model_name='treino',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.tipotreino'),
        ),
    ]
